name: "Update versions.json"
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 */1 * *'

jobs:
  update-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run update.py
        run: ./update.py
      - name: Generate commit message
        id: gen_commit
        run: |
          {
            echo 'COMMIT_MSG<<EOF'
            ./.github/commit_msg.sh
            echo EOF
          } >> "$GITHUB_ENV"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MSG }}
